### ISSUE TITLE
How fast is x264-rs comparing to libx264?

### ISSUE THREAD

**Issue by alishir** [quadrupleslap/x264#1]
Hi @quadrupleslap 

Thanks for your kind wrapper. Does any performance comparison available between x264-rs and libx264?

Regards,
Ali

**Comment by quadrupleslap** [comment]
I just added some asserts to avoid undefined behavior, but the cost of that should be negligible compared to the much more expensive stuff x264 itself does.

**Comment by CoolOppo** [comment]
Have you done any benchmarks?
