### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by samnystrom** [quadrupleslap/x264#7]
It seems like this crate is unmaintained. I would be interested in maintaining it, and for now I will publish and maintain my fork of it under the name `x264-next`. If you would be interested in transferring ownership of this crate or plan to maintain it, just let me know.

**Comment by quadrupleslap** [comment]
If no one responds to [this post](https://www.reddit.com/r/rust/comments/ylozoq), I'll hand over maintainership in two days. Does that sound good to you?

**Comment by samnystrom** [comment]
Sounds good!

**Comment by samnystrom** [comment]
You might want to repost that, it says it was removed by Reddit's spam filters.

**Comment by quadrupleslap** [comment]
Sorry I'm late!

* Regarding the spam filters, it's fine.
* I `cargo owner --add`ed you.
* Consider following kornel's suggestion at https://users.rust-lang.org/t/bus-factor-1-for-crates/17046

**Comment by samnystrom** [comment]
Yeah, I totally agree with that post. Thanks for responding to this issue so quickly! In the future, should I communicate with you using the email on your GitHub profile or do you have another preferred mode of contact? Also, would you like me to discuss any releases with you before publishing, and do you have any important info or advice about the crate?

**Comment by quadrupleslap** [comment]
> the email on your GitHub profile

Yeah, that's fine.

> do you have any important info or advice about the crate?

Sorry, it's been *way* too long for me to remember any details about this wrapper. 

> would you like me to discuss any releases with you before publishing

No, it's fine. Good luck! :slightly_smiling_face:

**Comment by samnystrom** [comment]
Thanks!
